# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "3.2"
# command to install dependencies
install: "pip install cherrypy --use-mirrors"

# prepare test run: install locally
before_script:
  - python setup.py -q sdist --keep-temp
  - cd `ls | grep CherryMusic`
  - python setup.py -q install
  - INSTALLDIR=/home/travis/virtualenv/python3.2/lib/python3.2/site-packages
  
# command to run tests
script:  ls $INSTALLDIR | grep cherry
#python -m unittest discover --failfast -s ${INSTALLDIR}/cherrymusicserver/test -t ${INSTALLDIR}
#setup.py -v test -q --test-suite cherrymusicserver.test

branches:
  # whitelist
  only:
    - master
    - devel
    - ci-experimental

notifications:
  email:
    recipients:
      - tilman.boerner@gmx.de
    on_success: never  # [always|never|change] # default: change
    on_failure: never  # [always|never|change] # default: always
