# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "3.2"
# command to install dependencies
install: "pip install cherrypy --use-mirrors"

# prepare test run: install locally
before_script:
  - python setup.py sdist --keep-temp
  - cd `ls | grep CherryMusic`
  - python setup.py install
  
# command to run tests
script: python setup.py -v test -q --test-suite cherrymusicserver.test

branches:
  # whitelist
  only:
    - master
    - devel
    - ci-experimental

notifications:
  email:
    recipients:
      - tilman.boerner@gmx.de
    on_success: never  # [always|never|change] # default: change
    on_failure: never  # [always|never|change] # default: always
